### ISSUE TITLE
Try with different file formats, separate IO from calculation?

### ISSUE THREAD

**Issue by perrygeo** [alfalimajuliett/masters-thesis#1]
@alfalimajuliett Thanks for the great work and for putting the code on github! This was a great read and a very important comparison.

I had two questions:
- Have you run the same comparisons but with different file formats, specifically ArcInfo Grids and Erdas IMG files? It seems like arcpy might have better internal support for grids in particular. It would be interesting to see if rasterio would still have a speed advantage even using arcinfo's native format.
- Have you looked at benchmarking the loading, calculation and writing to disk as separate tasks? For instance, it appears that ArcInfo is just slow to read/write data but might _possibly_ do the calculations at a similar speed.

I don't have access to ArcGIS at the moment but I'd be happy to help with coding should you choose to pursue these questions in your thesis. Thanks!

**Comment by alfalimajuliett** [comment]
Here is one of the figures from my paper:
![readnwrite](https://cloud.githubusercontent.com/assets/10790951/13882563/fb19a488-ecf3-11e5-8971-80481ad3ed7d.jpg)
The highlighted clusters were the execution times for arcpy reading and writing a raster file and they are relatively fast compared to the other arcpy tasks. In the appendix the times are broken out by task (see reading_one_raster.py and writing_one_raster.py). If you subtract the median writing time from the other arcpy tasks, they’d still be higher than the rasterio tasks.

The setup block of the code was not as emphasized as the map algebra calculation. The benchmark runs the calculation 40 times for every time it runs the setup. 

It would be interesting to see the results using different file formats, but I no longer have an ArcGIS license since I finished my degree.

**Comment by perrygeo** [comment]
Thank you @alfalimajuliett - and congratulations!! :tada:
